config/routes.rb
Rails.application.routes.draw do
  resources :exports

  post "create_file" =>"exports#create_file"

  root "exports#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/export.rb
class Export < ApplicationRecord
  has_one_attached :file_csv
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exports_controller.rb
class ExportsController < ApplicationController
  require 'csv'
  before_action :set_export, only: [:show, :edit, :update, :destroy]

  # GET /exports
  # GET /exports.json
  def index
    @exports = Export.all
  end

  # GET /exports/1
  # GET /exports/1.json
  def show

    @export.file_csv.open do |file|
      @csv_content = CSV.read(file, headers: true).take(5)
    end
    @headers = @csv_content.first.headers
  end

  # GET /exports/new
  def new
    @export = Export.new
  end

  # GET /exports/1/edit
  def edit
  end

  # POST /exports
  # POST /exports.json
  def create
    @export = Export.new(export_params)

    respond_to do |format|
      if @export.save
        format.html { redirect_to @export, notice: 'Export was successfully created.' }
        format.json { render :show, status: :created, location: @export }
      else
        format.html { render :new }
        format.json { render json: @export.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exports/1
  # PATCH/PUT /exports/1.json
  def update
    respond_to do |format|
      if @export.update(export_params)
        format.html { redirect_to @export, notice: 'Export was successfully updated.' }
        format.json { render :show, status: :ok, location: @export }
      else
        format.html { render :edit }
        format.json { render json: @export.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exports/1
  # DELETE /exports/1.json
  def destroy
    @export.destroy
    respond_to do |format|
      format.html { redirect_to exports_url, notice: 'Export was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Creates a CSV file and stores it in active storage (S3)
  def create_file

    # Create a instance of Export
    @export = Export.new(model: "test programatic", name: "from app" )

    # Reference local folder to temporarily store the file and name
    file_path = "public/csv/"
    filename = "CSV_#{Time.now.strftime("%d_%b_%Y_%H%M")}.csv"

    # Create a csv file, rewind and close it
    csv_file = CSV.open("#{file_path}#{filename}", 'w')
    csv_file.rewind # Can add content here, such as headers
    csv_file.close

    # Attach it to the @export record
    @export.file_csv.attach(io: File.open("#{file_path}#{filename}"), filename: filename, content_type: "text/csv")

    # Save both
    @export.save

    # Redirect to root
    redirect_to root_path

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_export
      if params[:id] == "create_file"
        @export = Export.find(1)
      else
        @export = Export.find(params[:id])
      end
    end

    # Only allow a list of trusted parameters through.
    def export_params
      params.require(:export).permit(:model, :name, :file_csv)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exports_helper.rb
module ExportsHelper
end

app/views/exports/_form.html.erb
<%= form_with(model: export, local: true) do |form| %>
  <% if export.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(export.errors.count, "error") %> prohibited this export from being saved:</h2>

      <ul>
        <% export.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :file_csv %>
    <%= form.file_field :file_csv %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exports/edit.html.erb
<h1>Editing Export</h1>

<%= render 'form', export: @export %>

<%= link_to 'Show', @export %> |
<%= link_to 'Back', exports_path %>

app/views/exports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exports</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exports.each do |export| %>
      <tr>
        <td><%= export.model %></td>
        <td><%= export.name %></td>
        <% if export.file_csv.attached? %>
          <td><%= export.file_csv.filename %></td>
        <% else %>
          <td>No file attached</td>
        <% end %>
        <td><%= link_to 'Show', export %></td>
        <td><%= link_to 'Edit', edit_export_path(export) %></td>
        <td><%= link_to 'Destroy', export, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Export', new_export_path %>
<p>
  <%= link_to "Create file", create_file_path, method: :post %>
</p>

app/views/exports/new.html.erb
<h1>New Export</h1>

<%= render 'form', export: @export %>

<%= link_to 'Back', exports_path %>

app/views/exports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @export.model %>
</p>

<p>
  <strong>Name:</strong>
  <%= @export.name %>
</p>

<p>
  <strong>File:</strong>
  <%= @export.file_csv.filename %>
</p>

<%= link_to 'Edit', edit_export_path(@export) %> |
<%= link_to 'Back', exports_path %>


<p>
  <% @headers.each do |head| %>
    <%= head %>
  <% end %>
</p>

<% @csv_content.each do | row | %>
  <p>
    <%= row %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwsS3Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>